name: afc616
version: 1.21.0
appVersion: 6.9.0
description: DataDog Agent
keywords:
- monitoring
- alerting
- metric
home: https://www.datadoghq.com
icon: https://raw.githubusercontent.com/matthewbelisle-wf/afc616/master/poc.svg
sources:
- https://app.datadoghq.com/account/settings#agent/kubernetes
- https://github.com/DataDog/datadog-agent
maintainers:
- name: hkaj
  email: haissam@datadoghq.com
- name: irabinovitch
  email: ilan@datadoghq.com
- name: xvello
  email: xavier.vello@datadoghq.com
- name: charlyf
  email: charly@datadoghq.com
